CREATE TABLE `users` (
	`identifier` VARCHAR(50) NOT NULL COLLATE 'utf8mb4_general_ci',
	`name` VARCHAR(50) NOT NULL COLLATE 'utf8mb4_general_ci',
	`rp_xp` INT(11) NOT NULL DEFAULT '0',
	`rp_rank` INT(11) NOT NULL DEFAULT '1',
	PRIMARY KEY (`identifier`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `vehicles` (
	`id` INT(11) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
	`plate` VARCHAR(8) NOT NULL DEFAULT '00AAA000' COLLATE 'utf8mb4_general_ci',
	`owner` VARCHAR(50) NOT NULL COLLATE 'utf8mb4_general_ci',
	`name` TINYTEXT NOT NULL DEFAULT 'Saved vehicle' COLLATE 'utf8mb4_general_ci',
	`model` VARCHAR(50) NOT NULL COLLATE 'utf8mb4_general_ci',
	`color1` INT(11) NOT NULL DEFAULT '1',
	`color2` INT(11) NOT NULL DEFAULT '1',
	`livery` INT(11) NOT NULL DEFAULT -1,
	`wheel_type` INT(11) NOT NULL DEFAULT -1,
	`wheels_f` INT(11) NOT NULL DEFAULT -1,
	`e_1` TINYINT(4) NOT NULL DEFAULT '0',
	`e_2` TINYINT(4) NOT NULL DEFAULT '0',
	`e_3` TINYINT(4) NOT NULL DEFAULT '0',
	`e_4` TINYINT(4) NOT NULL DEFAULT '0',
	`e_5` TINYINT(4) NOT NULL DEFAULT '0',
	`e_6` TINYINT(4) NOT NULL DEFAULT '0',
	`e_7` TINYINT(4) NOT NULL DEFAULT '0',
	`e_8` TINYINT(4) NOT NULL DEFAULT '0',
	`e_9` TINYINT(4) NOT NULL DEFAULT '0',
	`e_10` TINYINT(4) NOT NULL DEFAULT '0',
	`e_11` TINYINT(4) NOT NULL DEFAULT '0',
	`e_12` TINYINT(4) NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`) USING BTREE,
	UNIQUE INDEX `plate` (`plate`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=59
;
